//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGenerator.Example
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContestQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContestQuestion()
        {
            this.ContestQuestionAnswers = new HashSet<ContestQuestionAnswer>();
            this.ParticipantAnswers = new HashSet<ParticipantAnswer>();
        }
    
        public int Id { get; set; }
        public int ContestId { get; set; }
        public string Text { get; set; }
        public bool AskOfficialParticipants { get; set; }
        public bool AskPracticeParticipants { get; set; }
        public int Type { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string RegularExpressionValidation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContestQuestionAnswer> ContestQuestionAnswers { get; set; }
        public virtual Contest Contest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipantAnswer> ParticipantAnswers { get; set; }
    }
}
