//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGenerator.Example
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineJudgeSystemEntities : DbContext
    {
        public OnlineJudgeSystemEntities()
            : base("name=OnlineJudgeSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AccessLog> AccessLogs { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Checker> Checkers { get; set; }
        public virtual DbSet<ContestCategory> ContestCategories { get; set; }
        public virtual DbSet<ContestQuestionAnswer> ContestQuestionAnswers { get; set; }
        public virtual DbSet<ContestQuestion> ContestQuestions { get; set; }
        public virtual DbSet<Contest> Contests { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<FeedbackReport> FeedbackReports { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<ParticipantAnswer> ParticipantAnswers { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<ProblemResource> ProblemResources { get; set; }
        public virtual DbSet<Problem> Problems { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<SourceCode> SourceCodes { get; set; }
        public virtual DbSet<Submission> Submissions { get; set; }
        public virtual DbSet<SubmissionType> SubmissionTypes { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<TestRun> TestRuns { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
    }
}
