//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGenerator.Example
{
    using System;
    using System.Collections.Generic;
    
    public partial class Problem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Problem()
        {
            this.ProblemResources = new HashSet<ProblemResource>();
            this.SourceCodes = new HashSet<SourceCode>();
            this.Submissions = new HashSet<Submission>();
            this.Tests = new HashSet<Test>();
            this.Tags = new HashSet<Tag>();
        }
    
        public int Id { get; set; }
        public Nullable<int> OldId { get; set; }
        public int ContestId { get; set; }
        public string Name { get; set; }
        public short MaximumPoints { get; set; }
        public int TimeLimit { get; set; }
        public int MemoryLimit { get; set; }
        public Nullable<int> SourceCodeSizeLimit { get; set; }
        public Nullable<int> CheckerId { get; set; }
        public int OrderBy { get; set; }
        public bool ShowResults { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool ShowDetailedFeedback { get; set; }
        public byte[] SolutionSkeleton { get; set; }
    
        public virtual Checker Checker { get; set; }
        public virtual Contest Contest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProblemResource> ProblemResources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SourceCode> SourceCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Submission> Submissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test> Tests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
