//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGenerator.Example
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Submission()
        {
            this.TestRuns = new HashSet<TestRun>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParticipantId { get; set; }
        public Nullable<int> ProblemId { get; set; }
        public Nullable<int> SubmissionTypeId { get; set; }
        public byte[] Content { get; set; }
        public bool IsCompiledSuccessfully { get; set; }
        public string CompilerComment { get; set; }
        public bool Processed { get; set; }
        public bool Processing { get; set; }
        public string ProcessingComment { get; set; }
        public int Points { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string FileExtension { get; set; }
        public string IpAddress { get; set; }
        public byte[] SolutionSkeleton { get; set; }
    
        public virtual Participant Participant { get; set; }
        public virtual Problem Problem { get; set; }
        public virtual SubmissionType SubmissionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestRun> TestRuns { get; set; }
    }
}
