//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGenerator.Example
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmissionType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubmissionType()
        {
            this.Submissions = new HashSet<Submission>();
            this.Contests = new HashSet<Contest>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsSelectedByDefault { get; set; }
        public int ExecutionStrategyType { get; set; }
        public int CompilerType { get; set; }
        public string AdditionalCompilerArguments { get; set; }
        public string Description { get; set; }
        public bool AllowBinaryFilesUpload { get; set; }
        public string AllowedFileExtensions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Submission> Submissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contest> Contests { get; set; }
    }
}
