//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGenerator.Example
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Test()
        {
            this.TestRuns = new HashSet<TestRun>();
        }
    
        public int Id { get; set; }
        public int ProblemId { get; set; }
        public byte[] InputData { get; set; }
        public byte[] OutputData { get; set; }
        public bool IsTrialTest { get; set; }
        public int OrderBy { get; set; }
    
        public virtual Problem Problem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestRun> TestRuns { get; set; }
    }
}
