//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGenerator.Example
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestRun
    {
        public int Id { get; set; }
        public int SubmissionId { get; set; }
        public int TestId { get; set; }
        public int TimeUsed { get; set; }
        public long MemoryUsed { get; set; }
        public int ResultType { get; set; }
        public string ExecutionComment { get; set; }
        public string CheckerComment { get; set; }
        public string ExpectedOutputFragment { get; set; }
        public string UserOutputFragment { get; set; }
    
        public virtual Submission Submission { get; set; }
        public virtual Test Test { get; set; }
    }
}
